using System.Collections.Generic;

namespace Simplic.ICR
{
    /// <summary>
    /// Output objects generated by the analyser
    /// </summary>
    public class ICRObject
    {
        #region Fields

        private IList<AssignedTag> tags;

        #endregion Fields

        #region Constructor

        /// <summary>
        /// Create new, empty icr object
        /// </summary>
        public ICRObject()
        {
            tags = new List<AssignedTag>();
        }

        #endregion Constructor

        #region Public Member

        /// <summary>
        /// List of available tags
        /// </summary>
        public IList<AssignedTag> Tags
        {
            get { return tags; }
        }

        #endregion Public Member
    }
}